export default async function TermsPage() {
  return (
    <div className="font-garamond">
      <main className="flex flex-col items-center justify-start p-24">
        <h1 className="text-3xl font-bold mb-4">
          {`SQUIRE TERMS OF USE AGREEMENT`}
        </h1>
        <p>
          {`
            These Squire Terms of Service (“Terms”) govern your (“You” or “Your”) use of the Squire support platform and any related application programming interface (the “Squire” or “ Platform”) made available by Squire MD LLC (“Squire”, “We” “Our” or “Us”) that supports providers, and provider practices, in patient management through Squire Content (as defined below) on the Platform, as more fully described in these Terms (collectively, the “Squire Services”). These Terms describe your rights and responsibilities as a User (as defined below) of the Platform in connection with Your use of the Squire Services.
            
            PLEASE READ THESE TERMS CAREFULLY BY CLICKING “ACCEPT” OR ACCESSING OR USING THE PLATFORM, YOU AGREE TO BE BOUND BY THESE TERMS INCLUDING THE PRIVACY POLICY AND THE BUSINESS ASSOCIATE AGREEMENT WHICH ARE INCORPORATED INTO THESE TERMS. If You are not eligible, or do not agree to these Terms, then You do not have permission to access or use the Platform.
            
            UNLESS YOU ARE LOCATED IN A JURISDICTION THAT PROHIBITS THE EXCLUSIVE USE OF ARBITRATION FOR DISPUTE RESOLUTION, THESE TERMS PROVIDE THAT ALL DISPUTES BETWEEN YOU AND SQUIRE MD LLC REGARDING THESE TERMS WILL BE RESOLVED BY BINDING ARBITRATION. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT TO ASSERT OR DEFEND YOUR RIGHTS UNDER THIS AGREEMENT, EXCEPT FOR MATTERS THAT MAY BE TAKEN TO SMALL CLAIMS COURT. YOUR RIGHTS WILL BE DETERMINED BY A NEUTRAL ARBITRATOR AND NOT A JUDGE OR JURY, AND YOUR CLAIMS CANNOT BE BROUGHT AS A CLASS ACTION. PLEASE REVIEW SECTION 17 (“DISPUTE RESOLUTION AND ARBITRATION”) OF THESE TERMS FOR THE DETAILS REGARDING YOUR AGREEMENT TO ARBITRATE ANY DISPUTES WITH SQUIRE AND YOUR ABILITY TO OPT-OUT.
            
            Terms
            1. What These Terms Cover
            
            (a) Squire Platform
            These Terms govern the Squire Platform. These Terms include our Privacy Policy and, to the extent applicable, our Business Associate Agreement (“BAA”).
            
            2. Squire Platform
            
            (a) License.
            
            Subject to the restrictions set forth in these Terms, Squire grants You a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to use the Platform in connection with the Squire Services and to access other information related to conversations and visits shared with you from patients (“Patient Data”) on the Platform. You may use the Platform, subject to these Terms, solely for Your internal business purposes limited to training, patient care services, and evaluating the Platform for potential use in patient care services. You and not Squire shall be solely responsible to obtain Your patient’s consent to allow Squire to collect, store, and process Patient Data in any form for Squire to provide the Squire Services to You. You shall comply and require that Your employees comply with all applicable laws, rules and regulations, including HIPAA, with regard to patients’ rights to Patient Data stored by Squire under these Terms.
            
            (b) Account.‍
            
            Once You create a Squire account on the Platform (“Squire Account”), You will be considered a “User”. You should be the sole user of your Squire Account. You are fully responsible and liable for Your employees’ compliance with these Terms and unauthorized use of your Squire Account.
            
            (c) Use of the Squire Platform.‍
            
            Before using the Platform, You will need to create an account. If You register for an account by way of a third party, such as a hospital with which you are affiliated, personal information You provided to that third party, such as Your name, phone number, email address and other information that third party allows us to access, will be used to create Your account with us, along with information that You provide to us directly. If You already have an account with Us which was created independently (including by way of our “self-serve” onboarding) and then are invited to join by a third party such as a hospital with which you are affiliated and who has a written agreement with Us, You will have access to the information stored independently previously by way of one Platform account, but the third party, once there is a master agreement in place, will control Your account with respect to activity under that master agreement and on behalf of that entity including that such third party will have the ability to suspend and/or terminate Your account connected to such third party’s master agreement, provided however, notwithstanding any master agreement, Your account and use of the Platform will remain subject to all of these Terms. If, at any time, you are no longer affiliated with the third party, You will have the ability to revert back to Your independent (or ‘self-serve’) account.
            
            You are solely responsible for Your account information and any data that You provide to Us in connection with Your account (“Account Data”). You agree that You own or have the necessary rights, permissions and consents to all of Your Account Data and that use of the Account Data does not infringe, misappropriate or violate any third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable laws, rules or regulations. You are solely responsible for receiving and managing any necessary consent or authorization needed to utilize Squire with your patients. You agree to grant us a worldwide, non-exclusive license to access, use, export, process, copy, distribute, perform and display the Account Data in accordance these Terms including to provide, maintain and support the Squire Services, to prevent or respond to security issues, to provide support or respond to technical issues, as required by law, as permitted by these Terms and as permitted by Your instructions. You are responsible for safeguarding Your account login credentials. You are also responsible for all of the activity within Your account, whether or not You authorized that activity. We will not be responsible for any damages, losses or liability if credentials or any account is not kept confidential by You, or information provided by an unauthorized third party logging into and accessing the Platform. You should immediately notify us of any unauthorized access to or use of Your account. We may review activity in connection with the Platform for compliance purposes, but we have no obligation to do so. We aren't responsible for the content of any Account Data or the way You use the Platform to transmit, store or process any Account Data. If we believe, however, that there is a violation of these Terms, we may suspend or block the Platform or take any steps that we determine necessary, including with respect to Account Data, if we believe there is or may be a violation of any laws, rules or regulations or a risk of harm to Us, the Platform, any patient, other users or any third party.
            
            ‍(d) Communications.
            
            By accessing or using the Platform, You consent to the use of Your Account Data to contact You via email, text message (SMS) or other electronic means in connection with the provision of the Squire Services. Standard text or data charges may apply to communications. By registering for an account, You agree that such registration constitutes Your electronic signature, and You consent to electronic provision of all disclosures and notices from Us including those required by law. You also agree that Your electronic consent will have the same legal effect as a physical signature. You agree that we can provide notices regarding the Squire Services to You through the Platform (including Your account), or by mailing notice to the email address identified in Your account. Notices may include notifications about Your account, changes to the Squire Services, or other information we are required to provide to You. You also agree that electronic delivery of a notice has the same legal effect as if we provided You with a physical copy. We will consider a notice to have been received by You within twenty-four (24) hours of the time a notice is either posted to the Platform or emailed to You. You also authorize us to provide notices to You via text (SMS) message to allow us to verify Your control over Your account and to provide You with notices about Your account and/or Your interactions with patients. Standard text or data charges may apply to such notices. Where offered, You may disable text message notifications by responding to any such message with “STOP”, or by following instructions provided in the message. However, by disabling text messaging, You may be disabling important features of the Squire Services and You therefore assume any risk of such disablement.
            
            (e) Acceptable Use Policy.
            
            You may only use the Platform in compliance with applicable federal, state, local and international laws, rules and regulations and our Acceptable Use Policy (“AUP”) described below. You agree that we have the right to investigate violations of these Terms and may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.
            
            In using the Platform, You should refrain from any abusive, dangerous, or threatening behavior. We reserve the right to immediately suspend, block and/or terminate Your access to or use of the Platform if, in our sole discretion, such behavior is exhibited. As a condition of Your access to or use of the Platform, You agree to:
            i. Comply with the Terms and this AUP;
            ii. Comply with all applicable laws, rules and regulations;
            iii. Upload and use only Account Data which You own or to which You have obtained all required rights, waivers, permissions and consents and in accordance with all applicable laws, rule and regulations;
            iv. Prevent unauthorized access to or use of the Platform and keep passwords and all other login information to Your account secure and confidential;
            v. Promptly notify us if You become aware of or reasonably suspect any illegal or unauthorized activity or a security breach involving Your account, including any theft, loss, unauthorized access to, disclosure, or use of any login information or account; and
            vi. Comply with all terms applicable to any third party products and services, including any that You elect to use along with the Platform, if any.
            
            Further, as a condition of Your access to or use of the Platform, You will not:
            i. Attempt to reverse engineer, decompile, disable, disassemble, modify, copy, translate, or disrupt the features, functionality, integrity, or performance of the Platform, or sublicense, resell or time share the Platform;
            ii. Attempt to gain unauthorized access to all or a portion of the Platform, the networks or systems related to the Platform, or any data contained therein;
            iii. Interfere with another’s use of the Platform;
            iv. Permit access to the Platform by any third party;
            v. Rent, lease, lend, or grant a security interest in the Platform to any third party;
            vi. Provide the Platform to third parties in any service-bureau or similar capacity;
            vii. Disclose any user IDs, passwords, API keys or other similar access credentials to any third party;
            viii. Modify, copy, or make derivative works based on the Platform;
            ix. Upload to, or transmit from, the Platform any data, file, software, or link that contains or redirects to a worm, virus, Trojan horse or other harmful code or a technology that unlawfully accesses or downloads content or information stored within the Platform;
            x. Violate any applicable law, rules or regulations, the privacy rights of any third party or use the Platform to store or transmit any information that may infringe upon or misappropriate any third party intellectual property rights;
            xi. Post or transmit any Account Data or other content that is fraudulent or misleading;
            xii. Post, upload, share or distribute any content that is unlawful, defamatory, libelous, inaccurate, or that a reasonable person could deem to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate;
            xiii. Impersonate any person or entity or misrepresent Your affiliation with any person or entity;
            xiv. Access, search, or use any software or other tool or method to access, search, or download any intellectual property from the Platform by any means other than our approved interfaces (i.e., ‘scraping’);
            xv. “Frame” or “mirror” any of Squire’s content;
            xvi. Probe, scan, or test the vulnerability of any of our systems or networks, breach any security or authentication measures, or attempt to gain unauthorized access to the Platform, systems or networks including to circumvent any software, security protections or monitoring of the Services;
            xvii. Initiate a denial-of-service attack or a distributed denial-of-service attack, or otherwise attempt to interfere with the proper working of the Platform;
            xviii. Attempt to obtain personal information, or collect or record any information about users of the Platform;
            xix. Use the Platform except for Your own individual use for training, patient care services, and evaluating the Platform for potential use in patient care services;
            xx. Send or share any altered, deceptive or falsely sourced information, including ‘spoofing’ or ‘phishing’;
            xxi. Use the Platform in any manner that may harm any person or entity;
            xxii. Engage in activity that incites or encourages violence or hatred, or that discriminates;
            xxiii. Access or use the Platform in order to build a similar or competitive product or service;
            xxiv. Without Squire’s prior written consent, publish, disclose to any third party, or otherwise disseminate any benchmarking or other test results or similar data or reports, or other information, opinions, or results generated in connection with Your use of the Platform, including any comparisons of the Platform with alternative services or technology; or
            xxv. Authorize, permit, enable, induce or encourage any third party to do any of the above.
            
            3. Fees and Payment
            
            A Squire Account and the Platform may be provided to you free of cost through a third party partner, such as your health system or a health insurance company with whom you have a relationship. Please note, however, that if the Platform or any other services or products are provided to You, We reserve the right to make those services, updates, upgrades, new versions, or other products that incorporate those services (collectively, “Future Products”) available for a fee, and we will have no obligation to provide Future Products to You for free. Future Products may also be subject to separate fees and/or agreements for such Future Products. You acknowledge that you are responsible for all fees and expenses related to accessing or using the Platform including internet service provider fees.
            
            4. Ownership
            
            Squire and its licensors exclusively own and retain all rights, title and interest in and to, including all intellectual property rights therein and thereto the Squire Platform including the Platform and all websites, mobile applications, software, processes, algorithms, designs, user interfaces, look and feel, branding, documentation, specifications, application programming interfaces, and other technology provided or used in connection with or that constitutes the Squire Services (collectively, “Squire Technology”). Squire and its licensors reserve all rights not expressly granted in these Terms. No right or license is granted to make any improvements, derivative works, or modifications to the Platform or to any of the Squire’s Intellectual Property related to the Platform (“Improvements”). To the extent Improvement is made by the User or otherwise arises from the User’s use of or access to the Platform, all rights in such Improvement are hereby assigned to Squire. In the event this assignment fails for any reason, User grants to Squire a worldwide, perpetual, irrevocable, fully paid up, sublicensable (through multiple tiers), transferable license to practice such Improvement to Squire.
            
            5. Squire Content
            
            Squire owns all right, title and interest in and to all content provided by way of use of the Platform including all documentation and other information and content provided by Squire via the Platform which is accessible via the Squire website located notes.Squirescribe.com (“Squire Content“). The Squire Content is protected by copyright and other intellectual property laws throughout the world. All copyright and other proprietary notices on any Squire Content must be retained on any copies made thereof. Any unauthorized reproduction, modification, distribution, public display or public performance of any Squire Content is strictly prohibited.
            
            6. User Content
            
            (a) User Content Generally. Certain features of the Platform may permit You to upload content to the Platform (“User Content”). You retain the copyrights, including any moral rights, and any other proprietary rights that You may hold in the User Content.
            
            (b) Limited License Grant to Squire. By posting or publishing User Content, You grant Squire a perpetual, irrevocable, worldwide, non-exclusive, royalty-free, fully paid, transferable right and license (with the right to sublicense) to use User Content, in whole or in part, for any purpose in accordance with the Privacy Policy and any applicable laws (e.g., HIPAA).
            
            7. Business Associate Agreement
            
            The Parties agree that, to the extent Squire creates, receives, maintains, or transmits “protected health information” (as that term is defined by 45 C.F.R. 160.103) for or on behalf of You under these Terms, the BAA shall govern. The BAA is incorporated herein by reference, and made a part of these Terms.
            
            8. Privacy Policy; Additional Terms
            
            (a) Privacy Policy. Please read the Privacy Policy (“Privacy Policy”) carefully for information relating to Our collection, use, storage and disclosure of information for the Platform. The Privacy Policy is incorporated herein by reference, and made a part of these Terms.
            
            (b) Additional Terms. Your use of the Platform is subject to all additional terms, policies, rules, or guidelines applicable to the Platform or certain features of the Platform that We may post on or link to from the Platform (the “Additional Terms”), such as end-user license agreements for any downloadable software applications, or rules that are applicable to a particular feature or content on the Platform. All Additional Terms are incorporated by this reference into and made a part of these Terms.
            
            (c) Confidentiality. We both acknowledge that during the course of the transactions contemplated by these Terms, one of the parties (the “Disclosing Party”) may find it necessary or appropriate to share Confidential Information (as defined below) with the other Party (the “Receiving Party”). The Receiving Party will: (i) not use the Disclosing Party’s Confidential Information except for the exercise of its rights or performance of its obligations hereunder; (ii) not disclose such Confidential Information to any third party, other than its employees and consultants who have a “need to know” for the Receiving Party to exercise its rights or perform its obligations hereunder; and (iii) use at least reasonable measures to protect the confidentiality of such Confidential Information. If the Receiving Party is required by law to make any disclosure of such Confidential Information, the Receiving Party will first give written notice of such requirement to the Disclosing Party, and will permit the Disclosing Party to intervene in any relevant proceedings to protect its interests in the Confidential Information, and provide full cooperation to the Disclosing Party in seeking to obtain such protection. Information will not be deemed Confidential Information hereunder if such information: (1) is known or becomes known (independently of disclosure by the Disclosing Party) to the Receiving Party prior to receipt from the Disclosing Party from a source other than one having an obligation of confidentiality to the Disclosing Party; (2) becomes publicly known, except through a breach hereof by the Receiving Party; or (3) is independently developed by the Receiving Party without any use of or reference to the Disclosing Party’s Confidential Information. “Confidential Information” means any information provided by one Party to the other and concerning such Disclosing Party’s business or operations including, but not limited to, all tangible, intangible, visual, electronic, now existing or future information such as: (a) trade secrets; (b) financial information, including pricing of the Services; (c) technical information, including research, development, procedures, algorithms, data, designs, code, user interfaces, application programming interfaces, system performance information, and knowhow; (d) business information, including operations, planning, marketing interests, and products; and (e) all other information which would, due to the nature of the information disclosed or the circumstances surrounding such disclosure, appear to a reasonable person to be confidential or proprietary.
            
            9. Modifications to these Terms
            
            We reserve the right, at our discretion, to change these Terms on a going-forward basis at any time. Please check these Terms periodically for changes. If a change to these Terms materially modifies Your rights or obligations, we will use commercially reasonable efforts to notify You of the modified Terms by email or text message to the address or phone number You provided in setting up Your account. All modifications will be effective upon publication. Disputes arising under these Terms will be resolved in accordance with the version of these Terms that was in effect at the time the dispute arose. Your sole and exclusive remedy if You do not agree with any modification to these Terms is to terminate this Agreement in accordance with the terms herein. You may not amend or modify these Terms under any circumstances.
            
            10. Feedback
            
            Squire appreciates the ideas and suggestions of its Users. You may, but are not required to, provide Squire with information, suggestions, or other feedback with respect to the Squire Services, Platform (“Feedback”) and Squire may use such Feedback in any manner, including to improve its products and services. You hereby grant to Squire a worldwide, nonexclusive, perpetual, irrevocable, transferable, royalty free, fully paid up, sublicensable license to use and exploit Feedback for any purpose without restriction.
            
            11. Representations, Warranties, and Disclaimer
            
            (a) Mutual Representations.
            Each Party represents and warrants to the other Party that it has all necessary power and authority to enter into this Agreement and to carry out its obligations hereunder, and that the execution and performance of these Terms does not and will not conflict with or violate any law or its contractual or other obligations to any third party.
            
            (b) Squire’s Representations.
            Squire represents and warrants that it will provide the Platform in a professional manner consistent with applicable industry standards, and that the Platform will substantially conform in all material respects to user documentation provided by Squire for the Platform.
            
            (c) Your Representations.
            You represent and warrant that (i) You have the necessary rights and permissions or approvals to use and to permit the use of any information You provide to Squire hereunder; and (ii) You will not provide to Squire any personal data or personally identifiable information, as such terms are defined under applicable law, in violation of any contractual or other obligations, including Your privacy policies and guidelines, and applicable laws, including without limitation the Health Insurance Portability and Accountability Act.
            
            (d) Disclaimer.
            THE SQUIRE SERVICES ARE OFFERED AND PROVIDED “AS IS” AND ON AN “AS AVAILABLE” BASIS, WITHOUT WARRANTY OR CONDITION OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, Squire HEREBY DISCLAIMS ALL OTHER WARRANTIES IN CONNECTION WITH THESE TERMS, THE SQUIRE SERVICES, WHETHER IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, ACCURACY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, OR THAT THE SQUIRE SERVICES WILL BE AVAILABLE, COMPLETE, ADEQUATE, RELIABLE, ERROR-FREE OR UNINTERRUPTED. SQUIRE DOES NOT REVIEW, MONITOR, EVALUATE, OR ANALYZE ANY INFORMATION GENERATED FROM OR BY PATIENTS FOR ANY MEDICAL PURPOSE. SQUIRE DOES NOT ENGAGE IN THE PRACTICE OF MEDICINE AND DOES NOT PROVIDE ANY MEDICAL ADVICE OR DIAGNOSES TO PATIENTS. IT IS YOUR RESPONSIBILITY TO DISPENSE MEDICAL ADVICE TO OR MAKE DIAGNOSES FOR YOUR PATIENTS BASED ON YOUR PROFESSIONAL JUDGMENT, YOUR REVIEW OF ANY USER CONTENT OR PATIENT DATA USING THE SQUIRE SERVICES OR THE PLATFORM AND YOUR EVALUATION OF YOUR PATIENTS. BY USING THE PLATFORM, YOU CONSENT TO THE SELECTED COMMUNICATIONS CHANNELS YOU CHOOSE TO USE AND TO THE PROVIDER OF SUCH SERVICES. SUCH CONSENT INCLUDES YOUR AUTHORIZATION FOR THE SELECTED SERVICES, INCLUDING WITHOUT LIMITATION THE USE OF CERTAIN REMOTE-ACCESS COMMUNICATION FEATURES AND/OR FUNCTIONALITY INCLUDING, BUT NOT LIMITED TO, MOBILE, VIDEO, TEXT, AND/OR AUDIO, INFORMATION AND RECORDS FOR DELIVERING THE SELECTED SQUIRE SERVICES IN COMPLIANCE WITH APPLICABLE LAW. YOU ALSO AGREE THAT THE SQUIRE SERVICES ARE NOT INTENDED TO BE USED IN A MEDICAL EMERGENCY.
            
            12. Indemnification
            
            You will defend Us and our affiliates and our respective employees, partners, officers, directors, agents, successors and assigns (collectively, the “Indemnified Party(ies)”) from and against any and all third party claims, actions, suits, proceedings, and demands arising from or related to Your violation of the these Terms (including the or the AUP) (“Claim(s)”), and will indemnify the Indemnified Parties for all reasonable attorneys’ fees incurred and damages and other costs finally awarded against any Indemnified Party in connection with or as a result of, and for amounts paid by an Indemnified Party under a settlement You approve in connection with, a Claim. We agree to provide You with notice of any Claim and allow You the right to assume the exclusive defense and control, and cooperate with any reasonable requests in assisting Your defense and settlement of such Claim. Notwithstanding the foregoing, any Indemnified Parties may choose its own counsel if it pays for the cost of such counsel and You shall not enter into any settlement without the express written consent of the applicable Indemnified Party (such consent not to be unreasonably withheld).
            
            13. Limitations of Liability
            
            IN NO EVENT WILL WE OR OUR LICENSORS OR SUPPLIERS HAVE ANY LIABILITY TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFITS OR REVENUES OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, COVER OR PUNITIVE DAMAGES HOWEVER CAUSED, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, AND WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL OUR OR OUR LICENSORS OR SUPPLIERS’ AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS OR USE OF THE SQUIRE SERVICES OR PLATFORM BY YOU (WHETHER IN CONTRACT OR TORT OR UNDER ANY OTHER THEORY OF LIABILITY (INCLUDING NEGLIGENCE)) EXCEED $1,000. THE FOREGOING WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW. YOU AGREE THAT THE TERMS IN THIS LIMITATION OF LIABILITY SECTION ALLOCATES THE RISKS BETWEEN THE PARTIES, AND THE PARTIES HAVE RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO ENTER INTO THESE TERMS.
            
            14. Term and Termination
            
            The term of this Agreement begins on the date You agree to these Terms or use the Platform (“Effective Date”) and will continue until either Party terminates these Terms by way of notice to the other Party. If You are using the Platform by way of a controlling entity such as a health system, such third party may also terminate Your access to the Platform and access to Your Platform account. Squire may suspend or terminate access to the Platform or any account if Squire deems such suspension reasonably necessary to prevent any data breach or legal liability, without limiting any other remedies available at law or in equity.
            
            15. Dispute Resolution and Arbitration
            
            PLEASE READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE CERTAIN DISPUTES AND CLAIMS WITH US AND LIMITS THE MANNER IN WHICH YOU MAY SEEK RELIEF FROM US.‍
            
            (a) Generally. To the fullest extent permitted under applicable law and in the interest of resolving disputes between You and Squire in the most expedient and cost effective manner, You and Squire agree that every dispute arising in connection with these Terms will be resolved by binding arbitration, unless You are located in a jurisdiction that prohibits the exclusive use of arbitration for dispute resolution.
            
            Arbitration is less formal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. This agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of this Agreement, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of this Agreement. YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THIS AGREEMENT, YOU AND SQUIRE ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION, TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. ‍
            
            (b) Opt-Out of Agreement to Arbitrate. You can decline this agreement to arbitrate by contacting support@squirescribe.com within 30 days of first accepting this Agreement and stating that you (include your first and last name, and email address used to register for the Squire Platform) decline this arbitration agreement.‍
            
            (c) Exceptions. Despite the provisions of Section 15(a), nothing in these Terms will be deemed to waive, preclude, or otherwise limit the right of either Party to: (a) bring an individual action in small claims court; (b) pursue an enforcement action through the applicable federal, state, or local agency if that action is available; (c) seek injunctive relief in a court of law; or (d) to file suit in a court of law to address an intellectual property infringement claim.‍
            
            (d) Arbitrator. To the fullest extent permitted under applicable law, any arbitration between You and Squire will be settled under the Federal Arbitration Act, and governed by the Commercial Dispute Resolution Procedures and the Supplementary Procedures for Consumer Related Disputes (collectively, “AAA Rules”) of the American Arbitration Association (“AAA”), as modified by these Terms, and will be administered by the AAA. The AAA Rules and filing forms are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by contacting Squire.‍
            
            (e) Notice; Process. A party who intends to seek arbitration must first send a written notice of the dispute to the other party by certified U.S. Mail or by Federal Express (signature required) or, only if such other party has not provided a current physical address, then by electronic mail (“Notice”). Squire’s address for Notice is: Squire MD, LLC, 8 The Green, Ste A, Dover, DE 19901. The Notice must: (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought (“Demand”). The Parties will make good faith efforts to resolve the claim directly, but if the Parties do not reach an agreement to do so within 30 days after the Notice is received, You or Squire may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by You or Squire must not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. If the dispute is finally resolved through arbitration in Your favor, Squire will pay you the highest of the following: (i) the amount awarded by the arbitrator, if any; (ii) the last written settlement amount offered by Squire in settlement of the dispute prior to the arbitrator’s award; or (iii) $1,000.‍
            
            (f) Fees. If You commence arbitration in accordance with these Terms, Squire will reimburse You for Your payment of the filing fee, unless Your claim is for more than $10,000, in which case the payment of any fees will be decided by the AAA Rules. Any arbitration hearing will take place at a location, to be agreed upon, in Kent County, Delaware, but if the claim is for $10,000 or less, You may choose whether the arbitration will be conducted: (a) solely on the basis of documents submitted to the arbitrator; (b) through a non-appearance based telephone hearing; or (c) by an in-person hearing as established by the AAA Rules in the county (or parish) of your billing address. If the arbitrator finds that either the substance of Your claim or the relief sought in the Demand is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b), then the payment of all fees will be governed by the AAA Rules. In that case, You agree to reimburse Squire for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator must issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.‍
            
            (g) No Class Actions. TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW, YOU AND SQUIRE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both You and Squire agree otherwise, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding, to the fullest extent permissible pursuant to applicable law.‍
            
            (h) Claims. To the fullest extent permitted under applicable law, no action arising out of, in connection with, or relating to this Agreement shall be brought by You more than one (1) year after the accrual of the cause of action. This period shall not be extended for any reason, except by the written consent of both parties. All statutes or provisions of law which would toll or otherwise affect the running of the period of limitation are hereby waived, and no such statute or provision of law shall operate to extend the period limited in this paragraph, to the fullest extent permitted under applicable law.
            
            16. Modifications to this Arbitration Provision
            
            If Squire makes any future change to this arbitration provision, other than a change to Squire’s address for Notice, You may reject the change by sending us written notice within thirty (30) days of the change to Squire’s address for Notice, in which case Your account with Squire will be immediately terminated and this arbitration provision, as in effect immediately prior to the changes You rejected will survive.
            
            17. Enforceability
            
            If Section 15(f) is found to be unenforceable or if the entirety of Section 15 is found to be unenforceable, then the entirety of this Section 15 will be null and void and, in that case, the Parties agree that the exclusive jurisdiction and venue described in Section 18 will govern any action arising out of or related to these Terms.
            
            18. Miscellaneous
            
            (a) Governing Law; Venue. To the fullest extent permitted pursuant to applicable law, these Terms are governed by the laws of the State of Delaware without regard to conflict of law principles. If a lawsuit or court proceeding is permitted under this Agreement, then You and Squire agree to submit to the personal and exclusive jurisdiction of the state courts and federal courts located within Dover, Delaware for the purpose of litigating any dispute.
            
            (b) International Users. We operate the Platform from locations within the United States. The Platform is intended for Users located within the United States. We make no representation that the Platform or Squire Technology is appropriate or available for use outside of the United States. Access to the Platform from countries or territories or by individuals where such access is illegal is strictly prohibited.
            
            (c) Independent Contractors. The Parties are independent contractors. This Agreement does not establish any relationship of partnership, joint venture, employment, franchise or agency between You, Squire, and neither Party nor any third party will have the power to act on the other Party’s behalf without the other Party’s prior written consent.‍
            
            (d) Assignment. No Party shall have the right to assign this Agreement, in whole or in part, or any of its rights or obligations under this Agreement, without the prior written consent of the other Party (such consent not to be unreasonably withheld), except that Squire may assign this Agreement without consent as part of a corporate reorganization, reorganization, or upon a change of control, consolidation, merger, or transfer of all or substantially all of its business related to this Agreement, whether by sale of stock or assets, operation of law, or otherwise. Any attempted assignment or delegation in violation of the foregoing will be null and void.‍
            
            (e) Force Majeure. Except for the obligation to pay money, no Party will be liable for any failure or delay in its performance under this Agreement due to any cause beyond its reasonable control, including acts of war, acts of God, labor shortages or disputes, pandemics, governmental acts or failure or degradation of the Internet or telecommunications services. The delayed Party will give the other Party prompt notice of such cause, and will make commercially reasonable efforts to promptly correct such failure or delay in performance.
            
            (f) Severability; Waiver; Entire Agreement. If any provision of these Terms is held by a court of competent jurisdiction to be unenforceable, such provision shall be modified so as best to accomplish the original intent of the Parties to the fullest extent permitted by law, and the remaining provisions of these Terms shall remain in effect. The waiver of any breach or default of this Agreement will not constitute a waiver of any subsequent breach or default. This Agreement constitutes the entire agreement between the Parties with respect to the subject matter hereof, and supersedes all prior understandings and agreements.‍
            
            (g) Promotion. Squire may include Your name and logo in lists of Squire’s customers, solely to identify You as a user of the Platform and further provided that such customer lists shall not be presented in such a way as to indicate or imply any endorsement by or affiliation with You unless Squire obtains Your prior written consent.‍
            
            (h) Notices. Except as otherwise set forth herein, all notices under these Terms will be by email or provided by Us by way of the Platform. All notices to Us should be sent to support@squirescribe.com. Notices will be deemed to have been duly given the same day in the case of notices provided by us by way of email or the Services.
            
            (i) No Third Party Beneficiary. No person other than the Parties hereto will be entitled to any of the benefits of these Terms or be deemed to acquire any rights hereunder.
            
            (j) Export Compliance. The Squire Technology may be subject to export laws and regulations of the United States and other jurisdictions. You represent that You are not named on any U.S. government denied-party list. You shall not use the Squire Technology in violation of any U.S. export law or regulation.
            `}
        </p>
      </main>
    </div>
  );
}
